from app import create_app, db
from app.models import Part, User
from werkzeug.security import generate_password_hash

app = create_app()
with app.app_context():
    Part.query.delete()
    db.session.commit()

    parts = [
        Part(name="AMD Ryzen 5 5600X",brand="AMD",category="CPU",price=799.00,retailer="CZone",
             socket="AM4",power_draw=65,specs="6 Cores, 12 Threads, 3.7GHz Base, 4.6GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=AMD+Ryzen+5+5600X"),
        Part(name="AMD Ryzen 7 5800X",brand="AMD",category="CPU",price=1099.00,retailer="CZone",
             socket="AM4",power_draw=105,specs="8 Cores, 16 Threads, 3.8GHz Base, 4.7GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=AMD+Ryzen+7+5800X"),
        Part(name="AMD Ryzen 5 7600X",brand="AMD",category="CPU",price=1199.00,retailer="Harvey Norman",
             socket="AM5",power_draw=105,specs="6 Cores, 12 Threads, 4.7GHz Base, 5.3GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=AMD+Ryzen+5+7600X"),
        Part(name="Intel Core i5-12400F",brand="Intel",category="CPU",price=699.00,retailer="Harvey Norman",
             socket="LGA1700",power_draw=65,specs="6 Cores, 12 Threads, 2.5GHz Base, 4.4GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=Intel+i5+12400F"),
        Part(name="Intel Core i5-13400F",brand="Intel",category="CPU",price=799.00,retailer="CZone",
             socket="LGA1700",power_draw=65,specs="10 Cores, 16 Threads, 2.5GHz Base, 4.6GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=Intel+i5+13400F"),
        Part(name="Intel Core i7-13700K",brand="Intel",category="CPU",price=1699.00,retailer="Harvey Norman",
             socket="LGA1700",power_draw=125,specs="16 Cores, 24 Threads, 3.4GHz Base, 5.4GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=Intel+i7+13700K"),
        Part(name="Gigabyte RX 6600 Eagle 8GB",brand="Gigabyte",category="GPU",price=999.00,retailer="CZone",
             power_draw=132,specs="8GB GDDR6, 2491MHz Boost, 128-bit",
             buy_url="https://www.lazada.com.my/catalog/?q=RX+6600+Eagle"),
        Part(name="MSI RTX 3060 Ventus 2X 12GB",brand="MSI",category="GPU",price=1199.00,retailer="CZone",
             power_draw=170,specs="12GB GDDR6, 1777MHz Boost, 192-bit",
             buy_url="https://www.lazada.com.my/catalog/?q=RTX+3060+Ventus"),
        Part(name="ASUS Dual RX 7600 OC 8GB",brand="ASUS",category="GPU",price=1299.00,retailer="Harvey Norman",
             power_draw=165,specs="8GB GDDR6, 2755MHz Boost, 128-bit",
             buy_url="https://www.lazada.com.my/catalog/?q=RX+7600+ASUS"),
        Part(name="MSI RTX 4060 Gaming X 8GB",brand="MSI",category="GPU",price=1599.00,retailer="Harvey Norman",
             power_draw=115,specs="8GB GDDR6X, 2460MHz Boost, 128-bit",
             buy_url="https://www.lazada.com.my/catalog/?q=RTX+4060+Gaming+X"),
        Part(name="Gigabyte RTX 4070 WindForce 12GB",brand="Gigabyte",category="GPU",price=2499.00,retailer="CZone",
             power_draw=200,specs="12GB GDDR6X, 2475MHz Boost, 192-bit",
             buy_url="https://www.lazada.com.my/catalog/?q=RTX+4070+Gigabyte"),
        Part(name="Kingston Fury Beast 16GB DDR4-3200",brand="Kingston",category="RAM",price=249.00,retailer="CZone",
             ram_type="DDR4",specs="16GB (2x8GB), 3200MHz, CL16",
             buy_url="https://www.lazada.com.my/catalog/?q=Kingston+Fury+Beast+DDR4+16GB"),
        Part(name="Corsair Vengeance LPX 16GB DDR4-3600",brand="Corsair",category="RAM",price=299.00,retailer="Harvey Norman",
             ram_type="DDR4",specs="16GB (2x8GB), 3600MHz, CL18",
             buy_url="https://www.lazada.com.my/catalog/?q=Corsair+Vengeance+DDR4"),
        Part(name="G.Skill Trident Z5 16GB DDR5-6000",brand="G.Skill",category="RAM",price=549.00,retailer="CZone",
             ram_type="DDR5",specs="16GB (2x8GB), 6000MHz, CL36",
             buy_url="https://www.lazada.com.my/catalog/?q=GSkill+Trident+Z5+DDR5"),
        Part(name="Corsair Vengeance 32GB DDR5-5200",brand="Corsair",category="RAM",price=599.00,retailer="Harvey Norman",
             ram_type="DDR5",specs="32GB (2x16GB), 5200MHz, CL40",
             buy_url="https://www.lazada.com.my/catalog/?q=Corsair+Vengeance+DDR5+32GB"),
        Part(name="ASUS ROG Strix B550-F Gaming",brand="ASUS",category="Motherboard",price=899.00,retailer="CZone",
             socket="AM4",ram_type="DDR4",form_factor="ATX",specs="ATX, DDR4, PCIe 4.0, 2.5G LAN",
             buy_url="https://www.lazada.com.my/catalog/?q=ASUS+ROG+B550-F"),
        Part(name="MSI MAG B550 Tomahawk",brand="MSI",category="Motherboard",price=749.00,retailer="Harvey Norman",
             socket="AM4",ram_type="DDR4",form_factor="ATX",specs="ATX, DDR4, PCIe 4.0, 2.5G LAN",
             buy_url="https://www.lazada.com.my/catalog/?q=MSI+MAG+B550+Tomahawk"),
        Part(name="ASUS Prime B650M-A",brand="ASUS",category="Motherboard",price=899.00,retailer="Harvey Norman",
             socket="AM5",ram_type="DDR5",form_factor="mATX",specs="mATX, DDR5, PCIe 5.0, 2.5G LAN",
             buy_url="https://www.lazada.com.my/catalog/?q=ASUS+Prime+B650M"),
        Part(name="MSI PRO Z790-A WiFi",brand="MSI",category="Motherboard",price=1099.00,retailer="CZone",
             socket="LGA1700",ram_type="DDR5",form_factor="ATX",specs="ATX, DDR5, PCIe 5.0, WiFi 6E",
             buy_url="https://www.lazada.com.my/catalog/?q=MSI+PRO+Z790"),
        Part(name="Gigabyte B760M DS3H",brand="Gigabyte",category="Motherboard",price=599.00,retailer="CZone",
             socket="LGA1700",ram_type="DDR4",form_factor="mATX",specs="mATX, DDR4, PCIe 4.0, 1G LAN",
             buy_url="https://www.lazada.com.my/catalog/?q=Gigabyte+B760M+DS3H"),
        Part(name="Samsung 970 EVO Plus 500GB NVMe",brand="Samsung",category="Storage",price=249.00,retailer="CZone",
             specs="500GB NVMe PCIe 3.0, 3500MB/s Read",
             buy_url="https://www.lazada.com.my/catalog/?q=Samsung+970+EVO+Plus+500GB"),
        Part(name="WD Blue SN570 1TB NVMe",brand="Western Digital",category="Storage",price=299.00,retailer="Harvey Norman",
             specs="1TB NVMe PCIe 3.0, 3500MB/s Read",
             buy_url="https://www.lazada.com.my/catalog/?q=WD+Blue+SN570+1TB"),
        Part(name="Seagate Barracuda 1TB HDD",brand="Seagate",category="Storage",price=169.00,retailer="Harvey Norman",
             specs="1TB SATA, 7200RPM, 64MB Cache",
             buy_url="https://www.lazada.com.my/catalog/?q=Seagate+Barracuda+1TB"),
        Part(name="Samsung 980 Pro 1TB NVMe Gen4",brand="Samsung",category="Storage",price=499.00,retailer="CZone",
             specs="1TB NVMe PCIe 4.0, 7000MB/s Read",
             buy_url="https://www.lazada.com.my/catalog/?q=Samsung+980+Pro+1TB"),
        Part(name="Corsair CV550 550W 80+ Bronze",brand="Corsair",category="PSU",price=289.00,retailer="Harvey Norman",
             wattage=550,specs="550W, 80+ Bronze, Non-Modular",
             buy_url="https://www.lazada.com.my/catalog/?q=Corsair+CV550"),
        Part(name="Seasonic Focus GX-650 80+ Gold",brand="Seasonic",category="PSU",price=449.00,retailer="CZone",
             wattage=650,specs="650W, 80+ Gold, Fully Modular",
             buy_url="https://www.lazada.com.my/catalog/?q=Seasonic+Focus+GX+650"),
        Part(name="Corsair RM750x 80+ Gold",brand="Corsair",category="PSU",price=549.00,retailer="Harvey Norman",
             wattage=750,specs="750W, 80+ Gold, Fully Modular",
             buy_url="https://www.lazada.com.my/catalog/?q=Corsair+RM750x"),
        Part(name="be quiet! Pure Power 11 FM 850W",brand="be quiet!",category="PSU",price=649.00,retailer="CZone",
             wattage=850,specs="850W, 80+ Gold, Fully Modular",
             buy_url="https://www.lazada.com.my/catalog/?q=be+quiet+Pure+Power+850W"),
        Part(name="Lian Li LANCOOL 205 Mesh",brand="Lian Li",category="Case",price=349.00,retailer="CZone",
             form_factor="ATX",specs="Mid Tower, ATX/mATX, 2x140mm fans, Tempered Glass",
             buy_url="https://www.lazada.com.my/catalog/?q=Lian+Li+LANCOOL+205"),
        Part(name="Cooler Master MasterBox Q300L",brand="Cooler Master",category="Case",price=219.00,retailer="Harvey Norman",
             form_factor="mATX",specs="Micro Tower, mATX/ITX, 1x120mm fan",
             buy_url="https://www.lazada.com.my/catalog/?q=Cooler+Master+Q300L"),
        Part(name="NZXT H510 Flow",brand="NZXT",category="Case",price=429.00,retailer="CZone",
             form_factor="ATX",specs="Mid Tower, ATX/mATX, 2x120mm fans, USB-C",
             buy_url="https://www.lazada.com.my/catalog/?q=NZXT+H510+Flow"),
        Part(name="Fractal Design Pop Air",brand="Fractal Design",category="Case",price=389.00,retailer="Harvey Norman",
             form_factor="ATX",specs="Mid Tower, ATX/mATX, 3x120mm fans, Tempered Glass",
             buy_url="https://www.lazada.com.my/catalog/?q=Fractal+Design+Pop+Air"),

        # ── Additional CPUs ─────────────────────────────────────────────────
        Part(name="AMD Ryzen 3 4100",brand="AMD",category="CPU",price=399.00,retailer="CZone",
             socket="AM4",power_draw=65,specs="4 Cores, 8 Threads, 3.8GHz Base, 4.0GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=AMD+Ryzen+3+4100"),
        Part(name="AMD Ryzen 5 5500",brand="AMD",category="CPU",price=549.00,retailer="CZone",
             socket="AM4",power_draw=65,specs="6 Cores, 12 Threads, 3.6GHz Base, 4.2GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=AMD+Ryzen+5+5500"),
        Part(name="AMD Ryzen 7 7700X",brand="AMD",category="CPU",price=1599.00,retailer="Harvey Norman",
             socket="AM5",power_draw=105,specs="8 Cores, 16 Threads, 4.5GHz Base, 5.4GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=AMD+Ryzen+7+7700X"),
        Part(name="AMD Ryzen 9 5900X",brand="AMD",category="CPU",price=1799.00,retailer="CZone",
             socket="AM4",power_draw=105,specs="12 Cores, 24 Threads, 3.7GHz Base, 4.8GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=AMD+Ryzen+9+5900X"),
        Part(name="AMD Ryzen 9 7900X",brand="AMD",category="CPU",price=2199.00,retailer="Harvey Norman",
             socket="AM5",power_draw=170,specs="12 Cores, 24 Threads, 4.7GHz Base, 5.6GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=AMD+Ryzen+9+7900X"),
        Part(name="Intel Core i3-12100F",brand="Intel",category="CPU",price=449.00,retailer="CZone",
             socket="LGA1700",power_draw=58,specs="4 Cores, 8 Threads, 3.3GHz Base, 4.3GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=Intel+i3+12100F"),
        Part(name="Intel Core i5-13600K",brand="Intel",category="CPU",price=1299.00,retailer="Harvey Norman",
             socket="LGA1700",power_draw=125,specs="14 Cores, 20 Threads, 3.5GHz Base, 5.1GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=Intel+i5+13600K"),
        Part(name="Intel Core i9-13900K",brand="Intel",category="CPU",price=2999.00,retailer="CZone",
             socket="LGA1700",power_draw=125,specs="24 Cores, 32 Threads, 3.0GHz Base, 5.8GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=Intel+i9+13900K"),
        Part(name="Intel Core i3-13100F",brand="Intel",category="CPU",price=499.00,retailer="CZone",
             socket="LGA1700",power_draw=58,specs="4 Cores, 8 Threads, 3.4GHz Base, 4.5GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=Intel+i3+13100F"),
        Part(name="AMD Ryzen 5 7600",brand="AMD",category="CPU",price=999.00,retailer="CZone",
             socket="AM5",power_draw=65,specs="6 Cores, 12 Threads, 3.8GHz Base, 5.1GHz Boost",
             buy_url="https://www.lazada.com.my/catalog/?q=AMD+Ryzen+5+7600"),

        # ── Additional GPUs ──────────────────────────────────────────────────
        Part(name="Gigabyte RX 6500 XT Eagle 4GB",brand="Gigabyte",category="GPU",price=649.00,retailer="CZone",
             power_draw=107,specs="4GB GDDR6, 2610MHz Boost, 64-bit, PCIe 4.0",
             buy_url="https://www.lazada.com.my/catalog/?q=RX+6500+XT+Eagle"),
        Part(name="MSI RX 6650 XT Gaming X 8GB",brand="MSI",category="GPU",price=1099.00,retailer="Harvey Norman",
             power_draw=180,specs="8GB GDDR6, 2635MHz Boost, 128-bit, PCIe 4.0",
             buy_url="https://www.lazada.com.my/catalog/?q=RX+6650+XT+Gaming+X"),
        Part(name="ASUS TUF RX 6700 XT OC 12GB",brand="ASUS",category="GPU",price=1599.00,retailer="CZone",
             power_draw=230,specs="12GB GDDR6, 2581MHz Boost, 192-bit, PCIe 4.0",
             buy_url="https://www.lazada.com.my/catalog/?q=RX+6700+XT+TUF"),
        Part(name="Gigabyte RTX 3050 Eagle OC 8GB",brand="Gigabyte",category="GPU",price=899.00,retailer="Harvey Norman",
             power_draw=130,specs="8GB GDDR6, 1822MHz Boost, 128-bit, PCIe 4.0",
             buy_url="https://www.lazada.com.my/catalog/?q=RTX+3050+Eagle"),
        Part(name="MSI RTX 3070 Ventus 3X OC 8GB",brand="MSI",category="GPU",price=1999.00,retailer="CZone",
             power_draw=220,specs="8GB GDDR6, 1755MHz Boost, 256-bit, PCIe 4.0",
             buy_url="https://www.lazada.com.my/catalog/?q=RTX+3070+Ventus+3X"),
        Part(name="ASUS Dual RTX 4060 Ti 8GB",brand="ASUS",category="GPU",price=1999.00,retailer="Harvey Norman",
             power_draw=160,specs="8GB GDDR6X, 2535MHz Boost, 128-bit, PCIe 4.0",
             buy_url="https://www.lazada.com.my/catalog/?q=RTX+4060+Ti+ASUS"),
        Part(name="MSI RTX 4070 Ti Gaming X Trio 12GB",brand="MSI",category="GPU",price=3299.00,retailer="CZone",
             power_draw=285,specs="12GB GDDR6X, 2775MHz Boost, 192-bit, PCIe 4.0",
             buy_url="https://www.lazada.com.my/catalog/?q=RTX+4070+Ti+Gaming+X"),
        Part(name="Gigabyte RX 7700 XT Gaming OC 12GB",brand="Gigabyte",category="GPU",price=1799.00,retailer="Harvey Norman",
             power_draw=245,specs="12GB GDDR6, 2599MHz Boost, 192-bit, PCIe 4.0",
             buy_url="https://www.lazada.com.my/catalog/?q=RX+7700+XT+Gigabyte"),
        Part(name="ASUS ROG Strix RTX 4080 16GB",brand="ASUS",category="GPU",price=4999.00,retailer="Harvey Norman",
             power_draw=320,specs="16GB GDDR6X, 2625MHz Boost, 256-bit, PCIe 4.0",
             buy_url="https://www.lazada.com.my/catalog/?q=RTX+4080+ROG+Strix"),
        Part(name="MSI RX 6800 XT Gaming X Trio 16GB",brand="MSI",category="GPU",price=2499.00,retailer="CZone",
             power_draw=300,specs="16GB GDDR6, 2310MHz Boost, 256-bit, PCIe 4.0",
             buy_url="https://www.lazada.com.my/catalog/?q=RX+6800+XT+Gaming+X"),

        # ── Additional RAM ───────────────────────────────────────────────────
        Part(name="Kingston Fury Beast 8GB DDR4-3200",brand="Kingston",category="RAM",price=149.00,retailer="CZone",
             ram_type="DDR4",specs="8GB (1x8GB), 3200MHz, CL16",
             buy_url="https://www.lazada.com.my/catalog/?q=Kingston+Fury+Beast+8GB+DDR4"),
        Part(name="Corsair Vengeance LPX 32GB DDR4-3200",brand="Corsair",category="RAM",price=499.00,retailer="Harvey Norman",
             ram_type="DDR4",specs="32GB (2x16GB), 3200MHz, CL16",
             buy_url="https://www.lazada.com.my/catalog/?q=Corsair+Vengeance+LPX+32GB"),
        Part(name="G.Skill Ripjaws V 16GB DDR4-3600",brand="G.Skill",category="RAM",price=279.00,retailer="CZone",
             ram_type="DDR4",specs="16GB (2x8GB), 3600MHz, CL18",
             buy_url="https://www.lazada.com.my/catalog/?q=GSkill+Ripjaws+V+DDR4"),
        Part(name="G.Skill Ripjaws V 32GB DDR4-3600",brand="G.Skill",category="RAM",price=549.00,retailer="CZone",
             ram_type="DDR4",specs="32GB (2x16GB), 3600MHz, CL18",
             buy_url="https://www.lazada.com.my/catalog/?q=GSkill+Ripjaws+V+32GB"),
        Part(name="Kingston Fury Beast 32GB DDR5-5200",brand="Kingston",category="RAM",price=649.00,retailer="Harvey Norman",
             ram_type="DDR5",specs="32GB (2x16GB), 5200MHz, CL40",
             buy_url="https://www.lazada.com.my/catalog/?q=Kingston+Fury+Beast+DDR5+32GB"),
        Part(name="Teamgroup T-Force Vulcan 16GB DDR4-3200",brand="Teamgroup",category="RAM",price=229.00,retailer="CZone",
             ram_type="DDR4",specs="16GB (2x8GB), 3200MHz, CL16",
             buy_url="https://www.lazada.com.my/catalog/?q=Teamgroup+T-Force+Vulcan+DDR4"),
        Part(name="Crucial Pro 32GB DDR5-5600",brand="Crucial",category="RAM",price=599.00,retailer="Harvey Norman",
             ram_type="DDR5",specs="32GB (2x16GB), 5600MHz, CL46",
             buy_url="https://www.lazada.com.my/catalog/?q=Crucial+Pro+DDR5+32GB"),

        # ── Additional Motherboards ──────────────────────────────────────────
        Part(name="Gigabyte A520M DS3H",brand="Gigabyte",category="Motherboard",price=399.00,retailer="CZone",
             socket="AM4",ram_type="DDR4",form_factor="mATX",specs="mATX, DDR4, PCIe 3.0, 1G LAN",
             buy_url="https://www.lazada.com.my/catalog/?q=Gigabyte+A520M+DS3H"),
        Part(name="MSI B450M Pro-VDH Max",brand="MSI",category="Motherboard",price=449.00,retailer="Harvey Norman",
             socket="AM4",ram_type="DDR4",form_factor="mATX",specs="mATX, DDR4, PCIe 3.0, 1G LAN",
             buy_url="https://www.lazada.com.my/catalog/?q=MSI+B450M+Pro+VDH"),
        Part(name="ASUS TUF Gaming B550-PLUS",brand="ASUS",category="Motherboard",price=699.00,retailer="CZone",
             socket="AM4",ram_type="DDR4",form_factor="ATX",specs="ATX, DDR4, PCIe 4.0, 2.5G LAN",
             buy_url="https://www.lazada.com.my/catalog/?q=ASUS+TUF+B550-PLUS"),
        Part(name="Gigabyte B650 Aorus Elite AX",brand="Gigabyte",category="Motherboard",price=1199.00,retailer="Harvey Norman",
             socket="AM5",ram_type="DDR5",form_factor="ATX",specs="ATX, DDR5, PCIe 5.0, 2.5G LAN, WiFi 6E",
             buy_url="https://www.lazada.com.my/catalog/?q=Gigabyte+B650+Aorus+Elite"),
        Part(name="MSI MEG Z790 Ace",brand="MSI",category="Motherboard",price=2499.00,retailer="CZone",
             socket="LGA1700",ram_type="DDR5",form_factor="ATX",specs="ATX, DDR5, PCIe 5.0, 10G LAN, WiFi 6E, Thunderbolt 4",
             buy_url="https://www.lazada.com.my/catalog/?q=MSI+MEG+Z790+Ace"),
        Part(name="ASUS ROG Maximus Z790 Hero",brand="ASUS",category="Motherboard",price=2999.00,retailer="Harvey Norman",
             socket="LGA1700",ram_type="DDR5",form_factor="ATX",specs="ATX, DDR5, PCIe 5.0, 10G+2.5G LAN, WiFi 6E, Thunderbolt 4",
             buy_url="https://www.lazada.com.my/catalog/?q=ASUS+ROG+Maximus+Z790"),
        Part(name="MSI B550M Mortar",brand="MSI",category="Motherboard",price=599.00,retailer="CZone",
             socket="AM4",ram_type="DDR4",form_factor="mATX",specs="mATX, DDR4, PCIe 4.0, 2.5G LAN",
             buy_url="https://www.lazada.com.my/catalog/?q=MSI+B550M+Mortar"),
        Part(name="Gigabyte Z790 Aorus Master",brand="Gigabyte",category="Motherboard",price=1999.00,retailer="Harvey Norman",
             socket="LGA1700",ram_type="DDR5",form_factor="ATX",specs="ATX, DDR5, PCIe 5.0, 10G LAN, WiFi 6E",
             buy_url="https://www.lazada.com.my/catalog/?q=Gigabyte+Z790+Aorus+Master"),
        Part(name="ASUS Prime X570-P",brand="ASUS",category="Motherboard",price=649.00,retailer="CZone",
             socket="AM4",ram_type="DDR4",form_factor="ATX",specs="ATX, DDR4, PCIe 4.0, 1G LAN",
             buy_url="https://www.lazada.com.my/catalog/?q=ASUS+Prime+X570-P"),

        # ── Additional Storage ───────────────────────────────────────────────
        Part(name="Kingston NV2 500GB NVMe",brand="Kingston",category="Storage",price=179.00,retailer="CZone",
             specs="500GB NVMe PCIe 4.0, 3500MB/s Read",
             buy_url="https://www.lazada.com.my/catalog/?q=Kingston+NV2+500GB"),
        Part(name="Kingston NV2 1TB NVMe",brand="Kingston",category="Storage",price=279.00,retailer="CZone",
             specs="1TB NVMe PCIe 4.0, 3500MB/s Read",
             buy_url="https://www.lazada.com.my/catalog/?q=Kingston+NV2+1TB"),
        Part(name="Crucial MX500 500GB SATA SSD",brand="Crucial",category="Storage",price=199.00,retailer="Harvey Norman",
             specs="500GB SATA SSD, 560MB/s Read, 510MB/s Write",
             buy_url="https://www.lazada.com.my/catalog/?q=Crucial+MX500+500GB"),
        Part(name="Crucial MX500 1TB SATA SSD",brand="Crucial",category="Storage",price=329.00,retailer="Harvey Norman",
             specs="1TB SATA SSD, 560MB/s Read, 510MB/s Write",
             buy_url="https://www.lazada.com.my/catalog/?q=Crucial+MX500+1TB"),
        Part(name="WD Black SN850X 1TB NVMe Gen4",brand="Western Digital",category="Storage",price=579.00,retailer="CZone",
             specs="1TB NVMe PCIe 4.0, 7300MB/s Read, 6600MB/s Write",
             buy_url="https://www.lazada.com.my/catalog/?q=WD+Black+SN850X+1TB"),
        Part(name="Seagate Barracuda 2TB HDD",brand="Seagate",category="Storage",price=279.00,retailer="Harvey Norman",
             specs="2TB SATA, 7200RPM, 256MB Cache",
             buy_url="https://www.lazada.com.my/catalog/?q=Seagate+Barracuda+2TB"),
        Part(name="WD Blue 2TB HDD",brand="Western Digital",category="Storage",price=259.00,retailer="CZone",
             specs="2TB SATA, 5400RPM, 256MB Cache",
             buy_url="https://www.lazada.com.my/catalog/?q=WD+Blue+2TB"),
        Part(name="Samsung 870 EVO 500GB SATA SSD",brand="Samsung",category="Storage",price=259.00,retailer="Harvey Norman",
             specs="500GB SATA SSD, 560MB/s Read, 530MB/s Write",
             buy_url="https://www.lazada.com.my/catalog/?q=Samsung+870+EVO+500GB"),
        Part(name="Samsung 870 EVO 1TB SATA SSD",brand="Samsung",category="Storage",price=419.00,retailer="CZone",
             specs="1TB SATA SSD, 560MB/s Read, 530MB/s Write",
             buy_url="https://www.lazada.com.my/catalog/?q=Samsung+870+EVO+1TB"),
        Part(name="Crucial P3 2TB NVMe",brand="Crucial",category="Storage",price=449.00,retailer="Harvey Norman",
             specs="2TB NVMe PCIe 3.0, 3500MB/s Read",
             buy_url="https://www.lazada.com.my/catalog/?q=Crucial+P3+2TB"),

        # ── Additional PSUs ──────────────────────────────────────────────────
        Part(name="Thermaltake Smart 500W 80+ White",brand="Thermaltake",category="PSU",price=199.00,retailer="CZone",
             wattage=500,specs="500W, 80+ White, Non-Modular",
             buy_url="https://www.lazada.com.my/catalog/?q=Thermaltake+Smart+500W"),
        Part(name="Cooler Master MWE Gold 650W",brand="Cooler Master",category="PSU",price=349.00,retailer="Harvey Norman",
             wattage=650,specs="650W, 80+ Gold, Semi-Modular",
             buy_url="https://www.lazada.com.my/catalog/?q=Cooler+Master+MWE+Gold+650W"),
        Part(name="Cooler Master MWE Gold 750W",brand="Cooler Master",category="PSU",price=399.00,retailer="CZone",
             wattage=750,specs="750W, 80+ Gold, Semi-Modular",
             buy_url="https://www.lazada.com.my/catalog/?q=Cooler+Master+MWE+Gold+750W"),
        Part(name="ASUS ROG Thor 850W Platinum",brand="ASUS",category="PSU",price=899.00,retailer="Harvey Norman",
             wattage=850,specs="850W, 80+ Platinum, Fully Modular, OLED Display",
             buy_url="https://www.lazada.com.my/catalog/?q=ASUS+ROG+Thor+850W"),
        Part(name="Seasonic Prime TX-1000 Titanium",brand="Seasonic",category="PSU",price=1199.00,retailer="CZone",
             wattage=1000,specs="1000W, 80+ Titanium, Fully Modular",
             buy_url="https://www.lazada.com.my/catalog/?q=Seasonic+Prime+TX+1000"),
        Part(name="Corsair HX1000 Platinum",brand="Corsair",category="PSU",price=999.00,retailer="Harvey Norman",
             wattage=1000,specs="1000W, 80+ Platinum, Fully Modular, 10-year warranty",
             buy_url="https://www.lazada.com.my/catalog/?q=Corsair+HX1000"),
        Part(name="be quiet! Straight Power 11 750W",brand="be quiet!",category="PSU",price=549.00,retailer="CZone",
             wattage=750,specs="750W, 80+ Gold, Fully Modular",
             buy_url="https://www.lazada.com.my/catalog/?q=be+quiet+Straight+Power+11+750W"),

        # ── Additional Cases ─────────────────────────────────────────────────
        Part(name="Corsair 4000D Airflow",brand="Corsair",category="Case",price=449.00,retailer="CZone",
             form_factor="ATX",specs="Mid Tower, ATX/mATX, 2x120mm fans, Tempered Glass, USB-C",
             buy_url="https://www.lazada.com.my/catalog/?q=Corsair+4000D+Airflow"),
        Part(name="Lian Li O11 Dynamic EVO",brand="Lian Li",category="Case",price=699.00,retailer="Harvey Norman",
             form_factor="ATX",specs="Mid Tower, ATX/mATX, Dual Chamber, Tempered Glass",
             buy_url="https://www.lazada.com.my/catalog/?q=Lian+Li+O11+Dynamic+EVO"),
        Part(name="Fractal Design Meshify 2",brand="Fractal Design",category="Case",price=599.00,retailer="CZone",
             form_factor="ATX",specs="Mid Tower, ATX/mATX/E-ATX, High-Airflow Mesh, 3x140mm fans",
             buy_url="https://www.lazada.com.my/catalog/?q=Fractal+Design+Meshify+2"),
        Part(name="DeepCool CC560",brand="DeepCool",category="Case",price=199.00,retailer="Harvey Norman",
             form_factor="ATX",specs="Mid Tower, ATX/mATX, 4x120mm fans, Tempered Glass",
             buy_url="https://www.lazada.com.my/catalog/?q=DeepCool+CC560"),
        Part(name="Cooler Master HAF 700 EVO",brand="Cooler Master",category="Case",price=999.00,retailer="CZone",
             form_factor="ATX",specs="Full Tower, ATX/E-ATX, 3x200mm fans, Tempered Glass",
             buy_url="https://www.lazada.com.my/catalog/?q=Cooler+Master+HAF+700"),
        Part(name="Phanteks Eclipse P400A",brand="Phanteks",category="Case",price=349.00,retailer="Harvey Norman",
             form_factor="ATX",specs="Mid Tower, ATX/mATX, 3x120mm fans, Mesh Front Panel",
             buy_url="https://www.lazada.com.my/catalog/?q=Phanteks+Eclipse+P400A"),
        Part(name="Silverstone SUGO SG13 Mini",brand="Silverstone",category="Case",price=249.00,retailer="CZone",
             form_factor="ITX",specs="Mini Tower, Mini-ITX, 1x80mm fan, Compact Design",
             buy_url="https://www.lazada.com.my/catalog/?q=Silverstone+SUGO+SG13"),
        Part(name="Fractal Design Node 304",brand="Fractal Design",category="Case",price=389.00,retailer="Harvey Norman",
             form_factor="ITX",specs="Mini Tower, Mini-ITX, 2x92mm fans, Tool-free design",
             buy_url="https://www.lazada.com.my/catalog/?q=Fractal+Design+Node+304"),
        Part(name="NZXT H7 Flow",brand="NZXT",category="Case",price=549.00,retailer="CZone",
             form_factor="ATX",specs="Mid Tower, ATX/mATX, 2x120mm fans, Mesh + Tempered Glass",
             buy_url="https://www.lazada.com.my/catalog/?q=NZXT+H7+Flow"),
        Part(name="Corsair 5000D Airflow",brand="Corsair",category="Case",price=599.00,retailer="Harvey Norman",
             form_factor="ATX",specs="Mid Tower, ATX/mATX/E-ATX, 3x120mm fans, Tempered Glass, USB-C",
             buy_url="https://www.lazada.com.my/catalog/?q=Corsair+5000D+Airflow"),
    ]
    db.session.bulk_save_objects(parts)
    db.session.commit()
    print(f"Seeded {len(parts)} parts with buy links!")

    if not User.query.filter_by(email="admin@mypartpicker.com").first():
        db.session.add(User(
            username="admin",email="admin@mypartpicker.com",
            password=generate_password_hash("admin123"),is_admin=True
        ))
        db.session.commit()
        print("Admin account created.")
        print("  Email:    admin@mypartpicker.com")
        print("  Password: admin123")
    else:
        print("Admin already exists — skipped.")

    # ── Sample public gallery builds (so the Gallery isn't empty on first run) ──
    from app.models import Build
    Build.query.delete()
    db.session.commit()

    admin_user = User.query.filter_by(email="admin@mypartpicker.com").first()
    p = {part.name: part for part in Part.query.all()}

    def safe_get(name):
        return p.get(name)

    sample_builds = [
        Build(
            name="Budget Starter Build", user_id=admin_user.id,
            is_compatible=True, is_public=True,
            cpu_id=safe_get("Intel Core i5-12400F").id if safe_get("Intel Core i5-12400F") else None,
            motherboard_id=safe_get("Gigabyte B760M DS3H").id if safe_get("Gigabyte B760M DS3H") else None,
            ram_id=safe_get("Kingston Fury Beast 16GB DDR4-3200").id if safe_get("Kingston Fury Beast 16GB DDR4-3200") else None,
            storage_id=safe_get("Seagate Barracuda 1TB HDD").id if safe_get("Seagate Barracuda 1TB HDD") else None,
            psu_id=safe_get("Corsair CV550 550W 80+ Bronze").id if safe_get("Corsair CV550 550W 80+ Bronze") else None,
            case_id=safe_get("Cooler Master MasterBox Q300L").id if safe_get("Cooler Master MasterBox Q300L") else None,
            total_cost=(699.00 + 599.00 + 249.00 + 169.00 + 289.00 + 219.00),
        ),
        Build(
            name="Mid-Range Gaming Rig", user_id=admin_user.id,
            is_compatible=True, is_public=True,
            cpu_id=safe_get("AMD Ryzen 5 5600X").id if safe_get("AMD Ryzen 5 5600X") else None,
            gpu_id=safe_get("MSI RTX 3060 Ventus 2X 12GB").id if safe_get("MSI RTX 3060 Ventus 2X 12GB") else None,
            motherboard_id=safe_get("ASUS ROG Strix B550-F Gaming").id if safe_get("ASUS ROG Strix B550-F Gaming") else None,
            ram_id=safe_get("Corsair Vengeance LPX 16GB DDR4-3600").id if safe_get("Corsair Vengeance LPX 16GB DDR4-3600") else None,
            storage_id=safe_get("Samsung 970 EVO Plus 500GB NVMe").id if safe_get("Samsung 970 EVO Plus 500GB NVMe") else None,
            psu_id=safe_get("Seasonic Focus GX-650 80+ Gold").id if safe_get("Seasonic Focus GX-650 80+ Gold") else None,
            case_id=safe_get("Lian Li LANCOOL 205 Mesh").id if safe_get("Lian Li LANCOOL 205 Mesh") else None,
            total_cost=(799.00 + 1199.00 + 899.00 + 299.00 + 249.00 + 449.00 + 349.00),
        ),
        Build(
            name="High-End Workstation", user_id=admin_user.id,
            is_compatible=True, is_public=True,
            cpu_id=safe_get("Intel Core i7-13700K").id if safe_get("Intel Core i7-13700K") else None,
            gpu_id=safe_get("Gigabyte RTX 4070 WindForce 12GB").id if safe_get("Gigabyte RTX 4070 WindForce 12GB") else None,
            motherboard_id=safe_get("MSI PRO Z790-A WiFi").id if safe_get("MSI PRO Z790-A WiFi") else None,
            ram_id=safe_get("Corsair Vengeance 32GB DDR5-5200").id if safe_get("Corsair Vengeance 32GB DDR5-5200") else None,
            storage_id=safe_get("Samsung 980 Pro 1TB NVMe Gen4").id if safe_get("Samsung 980 Pro 1TB NVMe Gen4") else None,
            psu_id=safe_get("Corsair RM750x 80+ Gold").id if safe_get("Corsair RM750x 80+ Gold") else None,
            case_id=safe_get("NZXT H510 Flow").id if safe_get("NZXT H510 Flow") else None,
            total_cost=(1699.00 + 2499.00 + 1099.00 + 599.00 + 499.00 + 549.00 + 429.00),
        ),
    ]
    db.session.bulk_save_objects(sample_builds)
    db.session.commit()
    print(f"Seeded {len(sample_builds)} sample public builds for the Gallery!")

    print("\nDone! Run: python run.py")
